### ISSUE TITLE
[Bug]: mp3 files won't create properly

### ISSUE THREAD

**Issue by MaxTeiger** [elebumm/RedditVideoMakerBot#1357]
### Describe the bug

Hello ! 

I just ran the script on the commit [#82bd71d](https://github.com/elebumm/RedditVideoMakerBot/tree/82bd71d6a32f66699bf4ad4e2e1a39d0c9c4bcb5) but I got errors when the script tries to create the mp3 files. I got the following message(s) : 

```bash
╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Saving Text to MP3 files...                                                                                                                                                                  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
File not found: assets/temp/z5pkgk/mp3/2-0.part.mp3
File not found: assets/temp/z5pkgk/mp3/4-0.part.mp3
File not found: assets/temp/z5pkgk/mp3/11-0.part.mp3
File not found: assets/temp/z5pkgk/mp3/17-0.part.mp3
File not found: assets/temp/z5pkgk/mp3/43-0.part.mp3
Saving... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0 it/s  
Saved Text to MP3 files successfully.
```

But I don't have any `.mp3` file in the assets folder.

Here is my `config.toml` file : 

```toml
[settings]
allow_nsfw = false
theme = "dark"
times_to_run = 1
opacity = 0.9
transition = 0.2
storymode = false

[settings.background]
background_choice = "minecraft"

[settings.tts]
voice_choice = "tiktok"
aws_polly_voice = "Matthew"
streamlabs_polly_voice = "Matthew"
tiktok_voice = "en_us_006"
python_voice = "1"
py_voice_num = "2"
silence_duration = 0.3

[reddit.creds]
client_id = "***"
client_secret = "***"
username = "Physical_Pride_1406"
password = "***"
2fa = false

[reddit.thread]
random = false
subreddit = "AskReddit"
post_id = ""
max_comment_length = 500
post_lang = ""
min_comments = 20
```

Therefore, it seems that the file `parkour.mp4` is corrupted, because when the script ends, I have the following error : 
```bash
OSError: MoviePy error: failed to read the first frame of video file assets/temp/z5pkgk/background.mp4. That might mean that the file is corrupted. That may also mean that you are using a deprecated version of FFMPEG. On Ubuntu/Debian for instance the version in the repos is deprecated. Please update to a recent version from the website.
```

### Reproduction Steps

```bash
brew install ffmpeg
python main.py
```

### Expected behavior

The video should be created, and I should have mp3 files downloaded in my `assets` folder

### System Information

Operating System : macOS Ventura 13.0
Python version : Python 3.10.7
App version / Branch : develop - commit [82bd71d](https://github.com/elebumm/RedditVideoMakerBot/commit/82bd71d6a32f66699bf4ad4e2e1a39d0c9c4bcb5)

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
