### ISSUE TITLE
[Bug]: Error while generating ss

### ISSUE THREAD

**Issue by insane-alt** [elebumm/RedditVideoMakerBot#2299]
### Describe the bug

Getting this error when tring to generate ss using firefox headless browser
```bash
Sorry, something went wrong with this version! Try again, and feel free to report this issue at GitHub or the Discord community.                                │
│ Version: 3.3.0                                                                                                                                                  │
│ Error: Page.evaluate: TypeError: Cannot set properties of null (setting 'textContent')                                                                          │
│     at eval (eval at evaluate (:226:30), <anonymous>:1:101)                                                                                                     │
│     at UtilityScript.evaluate (<anonymous>:233:19)                                                                                                              │
│     at UtilityScript.<anonymous> (<anonymous>:1:44)                                                                                                             │
│ Config: {'allow_nsfw': False, 'theme': 'light', 'times_to_run': 1, 'opacity': 0.9, 'storymode': False, 'storymodemethod': 1, 'storymode_max_length': 1000,      │
│ 'resolution_w': 1080, 'resolution_h': 1920, 'zoom': 1.0, 'channel_name': 'Supa Guy', 'background': {'background_video': 'minecraft', 'background_audio':        │
│ 'lofi', 'background_audio_volume': 0.15, 'enable_extra_audio': False, 'background_thumbnail': False, 'background_thumbnail_font_family': 'arial',               │
│ 'background_thumbnail_font_size': 96, 'background_thumbnail_font_color': '255,255,255'}, 'tts': {'voice_choice': 'pyttsx', 'random_voice': True,                │
│ 'elevenlabs_voice_name': 'Bella', 'elevenlabs_api_key': 'REDACTED', 'aws_polly_voice': 'Matthew', 'streamlabs_polly_voice': 'Matthew', 'tiktok_voice':          │
│ 'en_us_001', 'tiktok_sessionid': 'REDACTED', 'python_voice': '1', 'py_voice_num': '2', 'silence_duration': 0.3, 'no_emojis': False}}       
```

### Reproduction Steps

- Clone the repo
- Installed python 3.10.17
- Installed requirements.txt
- Ran python main.py
- Filled in the creads as follows. I filled the ... acc to the  docs as well
```toml
[ai]
ai_similarity_enabled = false
ai_similarity_keywords = ""

[settings]
allow_nsfw = false
theme = "light"
times_to_run = 1
opacity = 0.9
storymode = false
storymodemethod = 1
storymode_max_length = 1000
resolution_w = 1080
resolution_h = 1920
zoom = 1.0
channel_name = "Supa Guy"

[settings.background]
background_video = "minecraft"
background_audio = "lofi"
background_audio_volume = 0.15
enable_extra_audio = false
background_thumbnail = false
background_thumbnail_font_family = "arial"
background_thumbnail_font_size = 96
background_thumbnail_font_color = "255,255,255"

[settings.tts]
voice_choice = "pyttsx"
random_voice = true
elevenlabs_voice_name = "Bella"
elevenlabs_api_key = "..."
aws_polly_voice = "Matthew"
streamlabs_polly_voice = "Matthew"
tiktok_voice = "en_us_001"
tiktok_sessionid = ""
python_voice = "1"
py_voice_num = "2"
silence_duration = 0.3
no_emojis = false

[reddit.creds]
client_id = "......"
client_secret = "......."
username = "...."
password = "......"
2fa = false

[reddit.thread]
random = true
subreddit = "AskReddit+Redditdev"
post_id = ""
max_comment_length = 500
min_comment_length = 1
post_lang = "en"
min_comments = 20
``` 
- And then i get the above error when it reaches the part to generate the headless browser ss.

_  instaled playwright and the deps as well

### Expected behavior

- SS should be generated and should continue with successful generation of the video.

### Screenshots

![Image](https://github.com/user-attachments/assets/e0720759-ad6c-4540-b6a6-0f1b8488c0e5)

### System Information

Operating System : CachyOS
Python version : Python 3.10.17
App version / Branch : latest master v3.3.0

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
